config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'static_pages#home', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#home', as: :unauthenticated_root
    end
  end
  resources :invoice_items
  resources :invoices do
    get 'clone'
  end
  resources :marinas
  resources :boats
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord

  has_many :boats
  has_many :invoices
  before_save :downcase_email

  validates :first_name,  presence: true, length: { maximum: 50 }
  validates :last_name,  presence: true, length: { maximum: 50 }
  validates :phone,  presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  def name
    [first_name, last_name].join(' ')
  end

  def phone=(val)
    super(val.gsub(/[^0-9]/, ""))
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.order('last_name ASC').page(params[:page]).per(15)
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :phone, :email, :address1, :address2, :city, :state, :zip_code)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client_boats.html.haml
%br
= link_to 'New Boat', new_boat_path(:client_id=>@client.id), class: "btn btn-sm btn-primary text-white"
- @client.boats.each do |boat|
  %div{:id => "accordion_#{boat.id}"}
    .card.mt-3.border-primary
      .card-header.bg-primary{:id => "collapse_#{boat.id}"}
        .row
          %div{:class => "col-.5"}
            %button.btn-xs{"data-target" => "#collapse_#{boat.id}_target", "data-toggle" => "collapse"}
              +
          .col-3.text-white
            %h5= boat.name.humanize
          .col-6.text-white
            %strong Marina:
            = boat.marina.name + " " + boat.marina.display_address
          .col
            = link_to 'View', boat, class: 'btn btn-sm float-right text-white'
      .collapse{:id => "collapse_#{boat.id}_target", "aria-labelledby" => "collapse_#{boat.id}", "data-parent" => "#accordion_#{boat.id}"}
        %ul.list-group.list-group-flush
          %li.list-group-item
            .row
              .col-3
                %b Manufacturer:
                = boat.manufacturer
              .col-3
                %b Model:
                = boat.model
              .col-3
                %b Year:
                = boat.year
              .col-3
                %b Registered #:
                = boat.identification
          %li.list-group-item
            .row
              .col-3
                %b Hailing Port:
                = boat.hailing_port
              .col-3
                %b Type:
                = boat.boat_type.humanize
              .col-3
                %b Configuration:
                = boat.configuration.humanize
              .col-3
                %b Construction:
                = boat.construction.humanize
              .col-3
          %li.list-group-item
            .row
              .col-3
                %b Engines:
                = boat.engine
              .col-3
                %b Engine Count:
                = boat.engine_count
              .col-3
                %b Propulsion:
                = boat.propulsion.humanize
              .col-3
                %b Fuel Type:
                = boat.fuel_type.humanize

app/views/clients/_client_invoices.html.haml
%br
= link_to "New Invoice", new_invoice_path(:client_id=>@client.id), class: "btn btn-sm btn-primary text-white"
%br
%table.table.table-striped
  %thead.Primary
    %tr
      %th Invoice #
      %th Boat
      %th Date
      %th Total
      %th Payment
      %th
      %th
      %th

  %tbody
    - @client.invoices.each do |invoice|
      %tr
        %td= invoice.id
        %td= invoice.boat.name
        %td= invoice.date
        %td= invoice.total
        %td= invoice.is_payed
        %td= link_to 'Show', invoice
        %td= link_to 'Edit', edit_invoice_path(invoice)
        %td= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }

app/views/clients/_client_personal.html.haml
%br
.row
  .col
    %p
      %b Phone:
      = @client.phone
  .col
    %p
      %b Email:
      = @client.email
.row
  .col
    %p
      %b Address 1:
      = @client.address1
  .col
    %p
      %b Address 2:
      = @client.address2
.row
  .col
    %p
      %b City:
      = @client.city
  .col
    %p
      %b State:
      = @client.state
  .col
    %p
      %b Zipcode:
      = @client.zip_code

= link_to 'Edit', edit_client_path(@client), :class => 'btn btn-sm btn-primary text-white'

app/views/clients/_form.html.haml
= form_for @client do |f|
  - if @client.errors.any?
    = render = errors_for(@client)
  %br
  .form-group-row
    = f.label :first_name, 'First Name', :class => "col-sm-2"
    = f.text_field :first_name, :class => 'col-sm-6'
  .form-group-row
    = f.label :last_name, 'Last Name', :class => "col-sm-2"
    = f.text_field :last_name, :class => 'col-sm-6'
  .form-group-row
    = f.label :phone, 'Phone #', :class => "col-sm-2"
    = f.text_field :phone, :class => 'col-sm-6'
  .form-group-row
    = f.label :email, 'Email', :class => "col-sm-2"
    = f.text_field :email, :class => 'col-sm-6'
  .form-group-row
    = f.label :address1, 'Address 1', :class => "col-sm-2"
    = f.text_field :address1, :class => 'col-sm-6'
  .form-group-row
    = f.label :address2, 'Address 2', :class => "col-sm-2"
    = f.text_field :address2, :class => 'col-sm-6'
  .form-group-row
    = f.label :city, 'City', :class => "col-sm-2"
    = f.text_field :city, :class => 'col-sm-6'
  .form-group-row
    = f.label :state, 'State', :class => "col-sm-2"
    = f.text_field :state, :class => 'col-sm-6'
  .form-group-row
    = f.label :zip_code, 'Zip Code', :class => "col-sm-2"
    = f.text_field :zip_code, :class => 'col-sm-6'
  %br
  .actions
    = f.submit 'Save', :class => "btn btn-sm btn-primary text-white"

app/views/clients/edit.html.haml
%br
%h3= @client.name
%br
= link_to "Back to #{@client.name}", @client, class: "btn btn-sm btn-primary text white"
\|
= link_to 'Back to Client List', clients_path, class: "btn btn-sm btn-primary text-white"
%br
= render 'form'

app/views/clients/index.html.haml
%br
%h3 Clients List
%br
.row
  .col
    =paginate(@clients)
  .col
    =link_to '+ Add Client', new_client_path, :class => "btn btn-sm btn-primary text-white float-right"
%table.table.table-striped
  %thead.Primary
    %tr
      %th Last name
      %th First name
      %th Phone
      %th Email
      %th
      %th

  %tbody
    - @clients.each do |client|
      %tr
        %td= client.last_name
        %td= client.first_name
        %td= client.phone
        %td= client.email
        %td= link_to 'View', client
        %td= link_to 'Edit', edit_client_path(client)

%br

app/views/clients/new.html.haml
%br
%h3 Add Client
%br
= link_to 'Back to Clients List', clients_path, :class => "btn btn-sm btn-primary text-white"
%br
= render 'form'

app/views/clients/show.html.haml
%br
.row
  .col
    %h4= @client.name
  .col
    = link_to 'Back to Clients List', clients_path, :class => 'btn btn-sm btn-primary text-white float-right'

%br
%nav
  .nav.nav-tabs{:id => 'nav-tab', :role => 'tab-list'}
    %a{:class => 'nav-item nav-link active', :id => 'nav-personal-tab', "data-toggle" => "tab", :href => "#nav-personal", :role => "tab", "aria-controls" => "nav-home", "aria-selected" => "true"} Personal
    %a{:class => 'nav-item nav-link', :id => 'nav-boat-tab', "data-toggle" => "tab", :href => "#nav-boats", :role => "tab", "aria-controls" => "nav-home", "aria-selected" => "false"} Boats
    %a{:class => 'nav-item nav-link', :id => 'nav-invoices-tab', "data-toggle" => "tab", :href => "#nav-invoices", :role => "tab", "aria-controls" => "nav-home", "aria-selected" => "false"} Invoices
.tab-content#nav-tabContent
  .tab-pane.fade.show.active{:id => "nav-personal", :role => "tabpanel", "aria-labelledby" => "nav-personal-tab"}
    = render 'client_personal'
  .tab-pane.fade{:id => "nav-boats", :role => "tabpanel", "aria-labelledby" => "nav-boats-tab"}
    = render 'client_boats'
  .tab-pane.fade{:id => "nav-invoices", :role => "tabpanel", "aria-labelledby" => "nav-invoices-tab"}
    = render 'client_invoices'