config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'static_pages#home', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#home', as: :unauthenticated_root
    end
  end
  resources :invoice_items
  resources :invoices do
    get 'clone'
  end
  resources :marinas
  resources :boats
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
end

app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_invoice_item, only: [:show, :edit, :update, :destroy]

  def index
    @invoice_items = InvoiceItem.all
  end

  def show; end

  def new
    @invoice_item = InvoiceItem.new
  end

  def edit; end

  def create
    @invoice_item = InvoiceItem.new(invoice_item_params)

    respond_to do |format|
      if @invoice_item.save
        format.html { redirect_to @invoice_item, notice: 'Invoice item was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_item }
      else
        format.html { render :new }
        format.json { render json: @invoice_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @invoice_item.update(invoice_item_params)
        format.html { redirect_to @invoice_item, notice: 'Invoice item was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_item }
      else
        format.html { render :edit }
        format.json { render json: @invoice_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @invoice_item.destroy
    respond_to do |format|
      format.html { redirect_to invoice_items_url, notice: 'Invoice item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_invoice_item
      @invoice_item = InvoiceItem.find(params[:id])
    end

    def invoice_item_params
      params.require(:invoice_item).permit(:invoice_id, :description, :unit_cost, :quantity, :discount, :amount)
    end
end

app/helpers/invoice_items_helper.rb
module InvoiceItemsHelper
end

app/views/invoice_items/_form.html.haml
= form_for @invoice_item do |f|
  - if @invoice_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invoice_item.errors.count, "error")} prohibited this invoice_item from being saved:"
      %ul
        - @invoice_item.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :invoice
    = f.text_field :invoice
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :unit_cost
    = f.text_field :unit_cost
  .field
    = f.label :quantity
    = f.number_field :quantity
  .field
    = f.label :discount
    = f.text_field :discount
  .field
    = f.label :amount
    = f.text_field :amount
  .actions
    = f.submit 'Save'

app/views/invoice_items/edit.html.haml
%h1 Editing invoice_item

= render 'form'

= link_to 'Show', @invoice_item
\|
= link_to 'Back', invoice_items_path

app/views/invoice_items/index.html.haml
%h1 Listing invoice_items

%table
  %thead
    %tr
      %th Invoice
      %th Description
      %th Unit cost
      %th Quantity
      %th Discount
      %th Amount
      %th
      %th
      %th

  %tbody
    - @invoice_items.each do |invoice_item|
      %tr
        %td= invoice_item.invoice
        %td= invoice_item.description
        %td= invoice_item.unit_cost
        %td= invoice_item.quantity
        %td= invoice_item.discount
        %td= invoice_item.amount
        %td= link_to 'Show', invoice_item
        %td= link_to 'Edit', edit_invoice_item_path(invoice_item)
        %td= link_to 'Destroy', invoice_item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Invoice item', new_invoice_item_path

app/views/invoice_items/new.html.haml
%h1 New invoice_item

= render 'form'

= link_to 'Back', invoice_items_path

app/views/invoice_items/show.html.haml
%p#notice= notice

%p
  %b Invoice:
  = @invoice_item.invoice
%p
  %b Description:
  = @invoice_item.description
%p
  %b Unit cost:
  = @invoice_item.unit_cost
%p
  %b Quantity:
  = @invoice_item.quantity
%p
  %b Discount:
  = @invoice_item.discount
%p
  %b Amount:
  = @invoice_item.amount

= link_to 'Edit', edit_invoice_item_path(@invoice_item)
\|
= link_to 'Back', invoice_items_path