config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'static_pages#home', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#home', as: :unauthenticated_root
    end
  end
  resources :invoice_items
  resources :invoices do
    get 'clone'
  end
  resources :marinas
  resources :boats
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/boat.rb
class Boat < ApplicationRecord

  BOAT_TYPES    = %w(power sail)
  CONFIGURATION = %w(ketch sloop yawl trawler sedan cabin cutty other)
  CONSTRUCTION  = %w(fiberglass wood cement steel other)
  FUEL_TYPE     = %w(gas diesel biodiesel other)
  PROPULSION    = %w(inboard outboard sterndrive other)
  belongs_to :client
  belongs_to :marina
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.order('name ASC').page(params[:page]).per(10)
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
  end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:name, :manufacturer, :model, :construction, :boat_type, :identification, :configuration,
                                   :fuel_type, :propulsion, :engine, :engine_count, :hailing_port, :client_id, :year, :marina_id)
    end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/_form.html.haml
= form_for @boat do |f|
  - if @boat.errors.any?
    = render = errors_for(@boat)
  %br
  .form-group-row
    = f.label :client_id, 'Client', :class => 'col-sm-2'
    - if (params[:client_id])
      = f.text_field :client_id, :value => Client.find(params[:client_id]).name, :disabled => true, :class => "col-sm-6"
      = f.hidden_field :client_id, :value => params[:client_id]
    - else
      = f.collection_select(:client_id, Client.all, :id, :name, class: "form-control")
  .form-group-row
    = f.label :marina_id, 'Marina', :class => 'col-sm-2'
    - if @boat.marina != nil
      = f.text_field :marina_id, :value => Marina.find(@boat.marina.id).name, :disabled => true, :class => "col-sm-6"
      = f.hidden_field :marina_id, :value => @boat.marina.id
    - else
      = f.collection_select(:marina_id, Marina.all, :id, :name, class: "form-control")
  .form-group-row
    = f.label :name, 'Boat Name', :class => 'col-sm-2'
    = f.text_field :name, :class => 'col-sm-6'
  .form-group-row
    = f.label :manufacturer, 'Manufacturer', :class => 'col-sm-2'
    = f.text_field :manufacturer, :class => 'col-sm-6'
  .form-group-row
    = f.label :model, 'Model', :class => 'col-sm-2'
    = f.text_field :model, :class => 'col-sm-6'
  .form-group-row
    = f.label :year, 'Year', :class => 'col-sm-2'
    = f.text_field :year, :class => 'col-sm-6'
  .form-group-row
    = f.label :identification, 'Registration #', :class => 'col-sm-2'
    = f.text_field :identification, :class => 'col-sm-6'
  .form-group-row
    = f.label :boat_type, 'Boat Type', :class => 'col-sm-2'
    = f.select :boat_type, Boat::BOAT_TYPES, :class => 'col-sm-6'
  .form-group-row
    = f.label :configuration, 'Boat Configuration', :class => 'col-sm-2'
    = f.select :configuration, Boat::CONFIGURATION, :class => 'col-sm-6'
  .form-group-row
    = f.label :construction, 'Boat Construction', :class => 'col-sm-2'
    = f.select :construction, Boat::CONSTRUCTION, :class => 'col-sm-6'
  .form-group-row
    = f.label :engine, 'Engines', :class => 'col-sm-2'
    = f.text_field :engine, :class => 'col-sm-6'
  .form-group-row
    = f.label :engine_count, '# of Engines', :class => 'col-sm-2'
    = f.number_field :engine_count, :class => 'col-sm-6'
  .form-group-row
    = f.label :propulsion, 'Propulsion', :class => 'col-sm-2'
    = f.select :propulsion, Boat::PROPULSION, :class => 'col-sm-6'
  .form-group-row
    = f.label :fuel_type, 'Fuel Type', :class => 'col-sm-2'
    = f.select :fuel_type, Boat::FUEL_TYPE, :class => 'col-sm-6'
  .form-group-row
    = f.label :hailing_port, 'Hailing Port', :class => 'col-sm-2'
    = f.text_field :hailing_port, :class => 'col-sm-6'
  %br
  .actions
    = f.submit 'Save', :class => "btn btn-sm btn-primary text-white"

app/views/boats/edit.html.haml
%br
%h3 Edit #{@boat.name}
%br
= link_to "Back to #{@boat.name}", @boat, class: 'btn btn-sm btn-primary'
\|
= link_to 'Back to Boats List', boats_path, class: 'btn btn-sm btn-primary'
%br
= render 'form'

app/views/boats/index.html.haml
%br
%h1 Boat List
%br
.row
  .col
    =paginate(@boats)
  .col
    = link_to '+ Add Boat', new_boat_path, :class => "btn btn-sm btn-primary text-white float-right"
%table.table.table-striped
  %thead.Primary
    %tr
      %th Boat Name
      %th Manufacturer
      %th Model
      %th Boat Type
      %th Vessel ID
      %th Client
      %th
      %th
      %th

  %tbody
    - @boats.each do |boat|
      %tr
        %td= boat.name.humanize
        %td= boat.manufacturer
        %td= boat.model
        %td= boat.boat_type.humanize
        %td= boat.identification
        %td= boat.client.name
        %td= link_to 'View', boat
        %td= link_to 'Edit', edit_boat_path(boat)
        %td= link_to 'Delete', boat, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/boats/new.html.haml
%br
%h3 Add Boat
%br
= link_to 'Back to Boats List', boats_path, class: 'btn btn-sm btn-primary'
= render 'form'

app/views/boats/show.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    Home
  %li.breadcrumb-item
    = link_to "#{@boat.client.name}", client_path(@boat.client)
%br
%h3 #{@boat.name}
%br
= link_to "Edit #{@boat.name}", edit_boat_path(@boat), class: 'btn btn-sm btn-primary text-white'
\|
= link_to 'Back to Boats List', boats_path, class: 'btn btn-sm btn-primary text-white'
%br
%br
.card
  .card-header.bg-primary.text-white
    .row
      .col
        %strong Owner:
        = @boat.client.name
      .col
        %strong Marina:
        = @boat.marina.name
  .card-body
    .row
      .col
        %strong Manufacturer:
        = @boat.manufacturer
      .col
        %strong Model:
        = @boat.model
      .col
        %strong Year:
        = @boat.year
      .col
        %strong Registration #
        = @boat.identification
    %hr
    .row
      .col
        %strong Boat Type:
        = @boat.boat_type.humanize
      .col
        %strong Boat Configuration:
        = @boat.configuration.humanize
      .col
        %strong Boat Construction:
        = @boat.construction.humanize
      .col
        %strong Hailing Port:
        = @boat.hailing_port
    %hr
    .row
      .col
        %strong Engines:
        = @boat.engine
      .col
        %strong # of Engines:
        = @boat.engine_count
      .col
        %strong Propulsion:
        = @boat.propulsion.humanize
      .col
        %strong Fuel Type:
        = @boat.fuel_type.humanize