config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :admins
  devise_scope :admin do
    authenticated :admin do
      root 'static_pages#home', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#home', as: :unauthenticated_root
    end
  end
  resources :invoice_items
  resources :invoices do
    get 'clone'
  end
  resources :marinas
  resources :boats
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.haml
%nav{:class => "navbar navbar-expand-lg navbar-dark bg-primary"}
  = link_to "KBS", root_path, :class => "navbar-brand"
  %button.navbar-toggler{:type => "button", "data-toggle" => "collapse", "data-target" => "#navbarSupportedContent", "aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation"}
    %span.navbar-toggler-icon
  - if admin_signed_in?
    #navbar.collapse.navbar-collapse{:id => "navbarSupportedContent"}
      %ul.navbar-nav.mr-auto
        = link_to "Clients", clients_path, {:class => "nav-link active"}
        = link_to "Boats", boats_path, {:class => "nav-link active"}
        = link_to "Marinas", marinas_path, {:class => "nav-link active"}
        = link_to "Invoices", invoices_path, {:class => "nav-link active"}
    %ul.navbar-nav.ml-auto
      = link_to 'Logout', destroy_admin_session_path, method: :delete, class: "btn btn-outline-light text-white"
  - else
    #navbar.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        = link_to 'Login', new_admin_session_path, class: "btn btn-outline-light text-white"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Boatwerks
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container.bg-light
      - flash.each do |name, msg|
        = content_tag :div, msg, :class => "alert alert-info"
      = yield